### ISSUE TITLE
destroy -f doesn't work

### ISSUE THREAD

**Issue by surskitt** [MunGell/vgm#1]
When using the destroy command with the -f flag, vagrant asks each time for confirmation:

> $ vgm pp destroy -f                                                                                                                                                                                  
    mq: Are you sure you want to destroy the 'mq' VM? [y/N] y

I haven't confirmed yet if other flags are ignored.

**Comment by MunGell** [comment]
Hi @sharktamer,

Thank you for the bug report, I will take a look
